In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Full_complex_sarah - Objects and References.csv')

In [3]:
df

,TIC,gaiadr3_source_id,epic_id,per,Rebull_2016,Stauffer_2017,Stauffer_2018,Rebull_2018,Zhan_2019,Rebull_2020,Koen_2020,Stauffer_2021,Koen_2021,Guenther_2022,Rebull_2022,Koen_2022,Popinchalk_2023,Bouma_2024,Popinchalk_2024
0,59129133.0,3.392549e+18,246676629.0,0.6253,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59091144.0,3.392554e+18,246682490.0,3.6324,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118769116.0,3.411342e+18,247343526.0,0.3568,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,175594111.0,6.045819e+18,203354381.0,0.5993,NaN,NaN,First CR determination,Included in table,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,322928171.0,6.048613e+18,203636498.0,0.7794,NaN,NaN,First CR determination,Included in table,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,245792696.0,3.312904e+18,210554781.0,11.4675,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,268510346.0,1.479407e+17,247888948.0,1.4853,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,NaN,246932950.0,2.6815,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,NaN,NaN,247857331.0,7.4762,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,3.308598e+18,246650193.0,2.9245,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dupes=df.duplicated(subset='TIC').values

In [5]:
df.insert(loc=1,column='TIC dupe',value=dupes)

In [6]:
df

,TIC,TIC dupe,gaiadr3_source_id,epic_id,per,Rebull_2016,Stauffer_2017,Stauffer_2018,Rebull_2018,Zhan_2019,Rebull_2020,Koen_2020,Stauffer_2021,Koen_2021,Guenther_2022,Rebull_2022,Koen_2022,Popinchalk_2023,Bouma_2024,Popinchalk_2024
0,59129133.0,False,3.392549e+18,246676629.0,0.6253,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59091144.0,False,3.392554e+18,246682490.0,3.6324,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118769116.0,False,3.411342e+18,247343526.0,0.3568,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,175594111.0,False,6.045819e+18,203354381.0,0.5993,NaN,NaN,First CR determination,Included in table,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,322928171.0,False,6.048613e+18,203636498.0,0.7794,NaN,NaN,First CR determination,Included in table,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,245792696.0,False,3.312904e+18,210554781.0,11.4675,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,268510346.0,False,1.479407e+17,247888948.0,1.4853,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,True,NaN,246932950.0,2.6815,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,NaN,True,NaN,247857331.0,7.4762,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,True,3.308598e+18,246650193.0,2.9245,NaN,NaN,NaN,NaN,NaN,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dupes=df.duplicated(subset='gaiadr3_source_id').values
df.insert(loc=3,column='gaia dupe',value=dupes)

In [8]:
df

,TIC,TIC dupe,gaiadr3_source_id,gaia dupe,epic_id,per,Rebull_2016,Stauffer_2017,Stauffer_2018,Rebull_2018,...,Rebull_2020,Koen_2020,Stauffer_2021,Koen_2021,Guenther_2022,Rebull_2022,Koen_2022,Popinchalk_2023,Bouma_2024,Popinchalk_2024
0,59129133.0,False,3.392549e+18,False,246676629.0,0.6253,NaN,NaN,First CR determination,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59091144.0,False,3.392554e+18,False,246682490.0,3.6324,NaN,NaN,First CR determination,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118769116.0,False,3.411342e+18,False,247343526.0,0.3568,NaN,NaN,First CR determination,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,175594111.0,False,6.045819e+18,False,203354381.0,0.5993,NaN,NaN,First CR determination,Included in table,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,322928171.0,False,6.048613e+18,False,203636498.0,0.7794,NaN,NaN,First CR determination,Included in table,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,245792696.0,False,3.312904e+18,False,210554781.0,11.4675,NaN,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,268510346.0,False,1.479407e+17,False,247888948.0,1.4853,NaN,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,True,NaN,True,246932950.0,2.6815,NaN,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,NaN,True,NaN,True,247857331.0,7.4762,NaN,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,True,3.308598e+18,False,246650193.0,2.9245,NaN,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dupes=df.duplicated(subset='epic_id').values
df.insert(loc=5,column='epic dupe',value=dupes)

In [10]:
df

,TIC,TIC dupe,gaiadr3_source_id,gaia dupe,epic_id,epic dupe,per,Rebull_2016,Stauffer_2017,Stauffer_2018,...,Rebull_2020,Koen_2020,Stauffer_2021,Koen_2021,Guenther_2022,Rebull_2022,Koen_2022,Popinchalk_2023,Bouma_2024,Popinchalk_2024
0,59129133.0,False,3.392549e+18,False,246676629.0,False,0.6253,NaN,NaN,First CR determination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59091144.0,False,3.392554e+18,False,246682490.0,False,3.6324,NaN,NaN,First CR determination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118769116.0,False,3.411342e+18,False,247343526.0,False,0.3568,NaN,NaN,First CR determination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,175594111.0,False,6.045819e+18,False,203354381.0,False,0.5993,NaN,NaN,First CR determination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,322928171.0,False,6.048613e+18,False,203636498.0,False,0.7794,NaN,NaN,First CR determination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,245792696.0,False,3.312904e+18,False,210554781.0,False,11.4675,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,268510346.0,False,1.479407e+17,False,247888948.0,False,1.4853,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,True,NaN,True,246932950.0,False,2.6815,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,NaN,True,NaN,True,247857331.0,False,7.4762,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,True,3.308598e+18,False,246650193.0,False,2.9245,NaN,NaN,NaN,...,First CR determination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.to_csv('dupes version.csv',index=False)